name: 'Node-Build'
description: 'build node or create dist folder'
outputs:
  build_path:
    description: 'Build path'
runs:
  using: 'composite'
  steps:
    - run: python3 ${{ github.action_path }}/main.py
      shell: bash
