name: 'Diff-Path'
description: 'get paths'
inputs:  
  current_commit:
    description: 'Context commit'
    required: true
  rootDir:
    description: 'root directory of tf'
    required: true
outputs:
  paths:
    description: 'Paths that have changed'
runs:
  using: 'node12'
  main: 'index.js'