name: Manual workflow

on: 
  workflow_dispatch

env:
  GITHUB_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  FONTAWESOME_NPM_AUTH_TOKEN : ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.3'
    
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:    
        path: |
          '**/node_modules'
          '~/.npm'
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-${{ hashFiles('package-lock.json') }}
          node-          
    
    - name: Install dependencies
      run: |                
        npm ci


  build:
    name: build
    runs-on: ubuntu-latest
    needs: install
    steps:

    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.3'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:    
        path: |
          '**/node_modules'
          '~/.npm'
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-${{ hashFiles('package-lock.json') }}
          node-

    - name: Build
      run: |      
        npm install --save webpack-merge  
        npm run build
     
    - name: Add Short_Sha Env
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.SHORT_SHA }}
        path: dist
