name: Front Workflow

on:
  push:
    branches:
      - master
      - homolog
      - develop
    paths-ignore:
      - 'terraform/**'
      - '.github/**'

env:
  GITHUB_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  FONTAWESOME_NPM_AUTH_TOKEN : ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    outputs:
      build_path: ${{steps.node_build.outputs.build_path}}
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.3'
    
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:    
        path: |
          '**/node_modules'
          '~/.npm'
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-${{ hashFiles('package-lock.json') }}
          node-          

    - name: Node Build
      id: node_build
      uses: terrainvest/.github/actions/node-build@master

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nodeDist
        path: ${{steps.node_build.outputs.build_path}}


  build:
    name: build
    runs-on: ubuntu-latest
    needs: install
    outputs:
      job_context: ${{ toJSON(job) }}
      workspace: ${{steps.get-workspace.outputs.WORKSPACE}}
    steps:

    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.3'

    - name: Get Profile
      id: get-workspace
      run: |
        branch_name=$(echo $GITHUB_REF | awk -F / '{print $3}')
        if [[ $branch_name == *"ma"* ]]; then profile="prd"
        elif [[ $branch_name == *"hom"* ]]; then profile="hml"
        else profile="dev"
        fi
        echo "::set-output name=WORKSPACE::$profile"
        echo "PROFILE=$profile" >> $GITHUB_ENV
        echo "CFID=${profile^^}_CFID" >> $GITHUB_ENV
        echo "BUCKET=${profile^^}_BUCKET" >> $GITHUB_ENV

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:    
        path: |
          '**/node_modules'
          '~/.npm'
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-${{ hashFiles('package-lock.json') }}
          node-

    - name: Sync Front
      uses: terrainvest/.github/actions/front-sync@master
      with:
        aws_profile: ${{ env.PROFILE }}
        folder_build: ${{ needs.install.outputs.build_path }}
        cf_id: ${{ secrets[env.CFID] }}
        bucket: ${{ secrets[env.BUCKET] }}

  if_failure:
    name: Notify Failure
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      WORKSPACE: ${{needs.build.outputs.workspace}}
      JOB_CONTEXT: ${{needs.build.outputs.job_context}}
    if: failure()
    steps:
      - uses: actions/checkout@v2
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@v1.0.4
        with:
          webhook_url: ${{ secrets.ACT_WEBHOOK }}
          overwrite: "{title: `Front Workflow`,
                    text: `**Workflow Actor:** ${{ github.actor }}\n\n
                          **Environment:** ${{env.WORKSPACE}}\n\n
                          **Branch:** ${{github.ref}}\n\n
                          **Repository:** ${{github.repository}}\n\n
                          **Action:** ${{github.event_name}}\n\n
                          **Bucket:** ${{ secrets[env.BUCKET] }}`}"
          job: ${{ env.JOB_CONTEXT }}
          needs: ${{ toJson(needs) }}

  if_success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      WORKSPACE: ${{needs.build.outputs.workspace}}
      JOB_CONTEXT: ${{needs.build.outputs.job_context}}
    if: success()
    steps:
      - uses: actions/checkout@v2
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@v1.0.4
        with:
          webhook_url: ${{ secrets.ACT_WEBHOOK }}
          overwrite: "{title: `Lambda Workflow`,
                    text: `**Workflow Actor:** ${{ github.actor }}\n\n
                          **Environment:** ${{env.WORKSPACE}}\n\n
                          **Branch:** ${{github.ref}}\n\n
                          **Repository:** ${{github.repository}}\n\n
                          **Action:** ${{github.event_name}}\n\n
                          **Bucket:** ${{ secrets[env.BUCKET] }}`}"
          job: ${{ env.JOB_CONTEXT }}
          needs: ${{ toJson(needs) }}
