name: TF-Plan

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
  pull_resquest:
    branches: 
      - master
    paths:
      - 'terraform/**'

env:
  TF_VERSION: 0.14.4
  GITHUB_AUTH_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

jobs:

  matrixBuilder:
    runs-on: ubuntu-latest
    name: "Matrix Builder"
    fail-fast: false
    outputs:
      matrix: ${{steps.set-matrix.output.matrix}}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: set-matrix
        uses: terrainvest/.github/actions/node-diff@master
        
