name: TF-WorkFlow

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/org/**'
      - 'terraform/dev/**'
      - 'terraform/hml/**'
      - 'terraform/prd/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'terraform/org/**'
      - 'terraform/dev/**'
      - 'terraform/hml/**'
      - 'terraform/prd/**'

env:
  TF_VERSION: 0.14.4
  GITHUB_AUTH_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

jobs:

  matrixBuilder:
    runs-on: ubuntu-latest
    name: Matrix Builder    
    outputs:
      path: ${{steps.set-matrix.outputs.path}}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: setMatrix
        id: set-matrix
        uses: terrainvest/.github/actions/node-diff@master
        with:
          current_commit: ${{github.sha}}
          rootDir: terraform

      - name: Show Generated Matrix
        run: echo "${{ steps.set-matrix.outputs.path }}"


  terraformJob:
    needs: matrixBuilder
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrixBuilder.outputs.path)}}
    runs-on: ubuntu-latest
    name: Terraform Job at ${{matrix.path}}
    defaults:
      run:
        shell: bash
        working-directory: ${{matrix.path}}
    env:
      WD: ${{matrix.path}}      
    steps:

      - name: Checkout
        uses: actions/checkout@v2        

      - name: Get Workspace
        id: get-workspace
        run: |
          IFS='/'
          read -ra ENV <<< ${{ env.WD }}
          echo "::set-output name=WORKSPACE::"${ENV[1]}""

      - name: Set ENV
        run: echo "WORKSPACE=${{steps.get-workspace.outputs.WORKSPACE}}" >> $GITHUB_ENV
      
      - name: Setup AWS Profile
        uses: terrainvest/.github/actions/setup-aws-py@master
        with:
          aws_profile: ${{ env.WORKSPACE }} 
          root_path: ~/
        env:        
          ORG_TF_AWS_KEY_ID: ${{ secrets.ORG_TF_AWS_KEY_ID }}
          ORG_TF_AWS_SECRET_KEY: ${{ secrets.ORG_TF_AWS_SECRET_KEY }}
          HML_TF_AWS_KEY_ID: ${{ secrets.HML_TF_AWS_KEY_ID }}
          HML_TF_AWS_SECRET_KEY: ${{ secrets.HML_TF_AWS_SECRET_KEY }}
          PRD_TF_AWS_KEY_ID: ${{ secrets.PRD_TF_AWS_KEY_ID }}
          PRD_TF_AWS_SECRET_KEY: ${{ secrets.PRD_TF_AWS_SECRET_KEY }}
      
      - name: Get S3 Key
        id: s3-key
        uses: terrainvest/.github/actions/config-backend@master
        with:
          path: ${{ env.WD }}
        
      - name: Setup Terraform backend
        run: |
          echo 'profile = "${{ env.WORKSPACE }}"' >> ${{ github.workspace }}/terraform/${{ env.WORKSPACE }}/backend.tfvars
          echo 'key = "${{ steps.s3-key.outputs.key }}"' >> ${{ github.workspace }}/terraform/${{ env.WORKSPACE }}/backend.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=${{ github.workspace }}/terraform/${{ env.WORKSPACE }}/backend.tfvars

      - name: Terraform Create Workspace
        id: workspace
        run: |          
          terraform workspace select ${{ env.WORKSPACE }} || terraform workspace new ${{ env.WORKSPACE }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -var='aws_profile=${{ env.WORKSPACE }}' -out=plan-file.tfplan
        continue-on-error: true   

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ env.GITHUB_AUTH_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>
            \`\`\`${process.env.PLAN}\`\`\`
            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: IF FAILURE
        if: steps.plan.outcome == 'failure'
        id: error
        run: echo "::error::Error at planning terraform in ${{env.WORKSPACE}}"

      - name: Terraform Apply
        if: steps.plan.outcome == 'success'
        id: apply
        run: |
          echo "::debug::Applying terraform in ${{env.WORKSPACE}}"
          terraform apply -auto-approve plan-file.tfplan

      - name: Delete AWS Credential
        run: rm -rf ~/.aws