name: Trigger-Front-React

on:
  push:
    branches:
      - master
      - homolog
      - develop
    paths-ignore:
      - 'terraform/**'
      - '.github/**'

  workflow_dispatch:
    inputs:
      environment:        
        required: false

jobs:

  frontDeploy:
    name: frontDeploy
    runs-on: ubuntu-latest
    steps:

      - name: Filter Branch
        id: filter
        run: |
          branch_name=$(echo $GITHUB_REF | awk -F / '{print $3}')
          input_name=${{github.event.inputs.environment}}

          echo "::set-output name=branchName::"$branch_name""

          if [[ input_name != "" ]]; then branch_name=$input_name
          fi

          if [[ $branch_name == *"ma"* || $branch_name == *"prod"* ]]; then nodeEnv="production"
          elif [[ $branch_name == *"hom"* ]]; then nodeEnv="homologation"
          elif [[ $branch_name == *"dev"* ]]; then nodeEnv="development"
          else nodeEnv="${{github.event.inputs.environment}}"
          fi
          echo "::set-output name=node_env::$nodeEnv"

          if [[ $branch_name == *"ma"* || $branch_name == *"prod"* ]]; then awsProfile="prd"
          elif [[ $branch_name == *"hom"* ]]; then awsProfile="hml"
          else awsProfile="dev"
          fi
          echo "::set-output name=aws_profile::$awsProfile"
          echo "CFID=${awsProfile^^}_CFID" >> $GITHUB_ENV
          echo "BUCKET=${awsProfile^^}_BUCKET" >> $GITHUB_ENV

      - name: Trigger Workflow
        uses: mvasigh/dispatch-action@main
        with:          
          token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          owner: terrainvest
          repo: terra.infra
          event_type: front-react
          message: |
            {
              "repo": "${{ github.repository }}",
              "branch": "${{ steps.filter.outputs.branchName }}",
              "aws_profile": "${{ steps.filter.outputs.aws_profile }}",
              "cf_id": "${{ secrets[env.CFID] }}",
              "node_env": "${{ steps.filter.outputs.node_env }}",
              "bucket": "${{ secrets[env.BUCKET] }}"
            }
