name: 'Create-package'
description: 'create package from js build'
inputs:
  aws_profile:
    description: 'Profile aws'
    required: true
  using_docker:
    description: 'Bool if update using docker package'
    required: true
  image_uri:
    description: 'Image to use'
    required: false
runs:
  using: 'composite'
  steps:
    - run: pip3 install -r ${{ github.action_path }}/requirements.txt
    - run: python3 ${{ github.action_path }}/main.py ${{ inputs.aws_profile }} ${{ inputs.using_docker }} -i ${{ inputs.image_uri }}
      shell: bash
